services:
  - type: web
    name: steel-behavior-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1